// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCharacter(arg1) {
  return window['go']['main']['App']['AddCharacter'](arg1);
}

export function AddNPC(arg1) {
  return window['go']['main']['App']['AddNPC'](arg1);
}

export function AddSessionLog(arg1) {
  return window['go']['main']['App']['AddSessionLog'](arg1);
}

export function DeleteCharacter(arg1) {
  return window['go']['main']['App']['DeleteCharacter'](arg1);
}

export function DeleteNPC(arg1) {
  return window['go']['main']['App']['DeleteNPC'](arg1);
}

export function DeleteSessionLog(arg1) {
  return window['go']['main']['App']['DeleteSessionLog'](arg1);
}

export function GetAllCombatants() {
  return window['go']['main']['App']['GetAllCombatants']();
}

export function GetCharacters() {
  return window['go']['main']['App']['GetCharacters']();
}

export function GetNPCs() {
  return window['go']['main']['App']['GetNPCs']();
}

export function GetSessionLogs() {
  return window['go']['main']['App']['GetSessionLogs']();
}

export function RollDice(arg1) {
  return window['go']['main']['App']['RollDice'](arg1);
}

export function UpdateCharacter(arg1) {
  return window['go']['main']['App']['UpdateCharacter'](arg1);
}

export function UpdateNPC(arg1) {
  return window['go']['main']['App']['UpdateNPC'](arg1);
}

export function UpdateSessionLog(arg1) {
  return window['go']['main']['App']['UpdateSessionLog'](arg1);
}
