// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddCharacter(arg1:main.Character):Promise<void>;

export function AddNPC(arg1:main.NPC):Promise<void>;

export function AddSessionLog(arg1:string):Promise<void>;

export function DeleteCharacter(arg1:number):Promise<void>;

export function DeleteNPC(arg1:number):Promise<void>;

export function DeleteSessionLog(arg1:number):Promise<void>;

export function GetAllCombatants():Promise<Array<main.Combatant>>;

export function GetCharacters():Promise<Array<main.Character>>;

export function GetNPCs():Promise<Array<main.NPC>>;

export function GetSessionLogs():Promise<Array<main.SessionLog>>;

export function RollDice(arg1:number):Promise<Array<number>>;

export function UpdateCharacter(arg1:main.Character):Promise<void>;

export function UpdateNPC(arg1:main.NPC):Promise<void>;

export function UpdateSessionLog(arg1:main.SessionLog):Promise<void>;
